export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const GET_TODO_LISTS = 'GET_TODO_LISTS';
export const CREATE_TODO_LIST = 'CREATE_TODO_LIST';
export const DELETE_TODO_LIST = 'DELETE_TODO_LIST';
export const CHANGE_TODO_LIST_NAME = 'CHANGE_TODO_LIST_NAME';

export const CREATE_LIST_ITEM = 'CREATE_LIST_ITEM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const CHANGE_LIST_ITEM_CHECKED = 'CHANGE_LIST_ITEM_CHECKED';
export const CHANGE_LIST_ITEM_TEXT = 'CHANGE_LIST_ITEM_TEXT';

export const DISCONNECTED = 'DISCONNECTED';
export const CONNECTED = 'CONNECTED';